const A='/assets/';
const app=document.querySelector('#app');
const nav=[
  ['home','⌂','Beranda'],['planning','☷','Planning'],['goals','◎','Goals'],['journal','✎','Journal'],
  ['ideas','✦','Ideas'],['projects','□','Projects'],['journey','↗','Journey']
];
const profileMenu=[['stats','Statistik'],['explore','Jelajahi'],['collection','Koleksi'],['about','Tentang EA PLAN'],['guide','Panduan']];
let state={user:null,supabase:null,active:'home',onStep:1,selected:[],menu:false,modal:null};

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const meta=()=>state.user?.user_metadata||{};
const key=k=>`ea_plan_${k}_${state.user?.id||'guest'}`;
function load(k,f=[]){try{return JSON.parse(localStorage.getItem(key(k))||'null')??f}catch{return f}}
function save(k,v){localStorage.setItem(key(k),JSON.stringify(v))}
function uid(){return `${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
function initials(){return (meta().name||state.user?.email||'EA').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),250)},2600)}

async function boot(){
  splash();
  state.supabase=await window.EA_SUPABASE_READY;
  if(state.supabase){
    const {data:{session}}=await state.supabase.auth.getSession(); state.user=session?.user||null;
    state.supabase.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;if(state.user)renderApp();else welcome()});
  }else state.user=JSON.parse(localStorage.getItem('ea_user')||'null');
  setTimeout(()=>state.user?renderApp():welcome(),1700);
}
function splash(){app.innerHTML=`<section class="splash"><div class="splashPhoto"></div><div class="splashShade"></div><div class="splashContent"><img src="${A}logo.png" class="splashLogo"><div class="splashLine"></div><div class="tag">YOUR PERSONALIZED PLANNING JOURNEY</div></div></section>`}

function welcome(){app.innerHTML=`<div class="authShell"><div class="authVisual"><div class="authPhoto"></div><div class="visualShade"></div><div class="visualBrand"><img src="${A}logo.png"><span>PLAN · CREATE · REFLECT · GROW</span></div><div class="visualText"><p class="eyebrow">RUANG UNTUK MENJALANI</p><h1>Rancang hidupmu.<br><em>Rawat perjalananmu.</em></h1><p>EA PLAN menyatukan rencana, target, karya, catatan, dan refleksi dalam satu ruang yang tenang.</p></div></div><div class="authPanel"><div class="authBox"><img src="${A}logo.png" class="authLogo"><p class="eyebrow">EA PLAN</p><h2>Mulai perjalananmu.</h2><p class="sub">Satu ruang untuk merencanakan langkah, mencipta karya, dan melihat pertumbuhanmu dari waktu ke waktu.</p><div class="form"><button class="goldBtn" onclick="register()">Buat Akun</button><button class="ghostBtn" onclick="login()">Sudah punya akun · Masuk</button></div><div class="authFoot">Privat untuk perjalananmu. Publik untuk karya yang ingin kamu bagikan.</div></div></div></div>`}
function register(){auth('register')} function login(){auth('login')}
function auth(mode){const reg=mode==='register';app.innerHTML=`<div class="authOnly"><div class="authBox authCard"><button class="backBtn" onclick="welcome()">← Kembali</button><img src="${A}logo.png" class="authLogo small"><p class="eyebrow">${reg?'MEMULAI RUANGMU':'SELAMAT DATANG KEMBALI'}</p><h2>${reg?'Buat akun.':'Masuk ke EA PLAN.'}</h2><p class="sub">${reg?'Bangun ruang perjalanan yang terasa milikmu.':'Lanjutkan rencana dan karya yang sedang kamu jalani.'}</p><form class="form" onsubmit="submitAuth(event,'${mode}')">${reg?'<div class="fieldRow"><label>Nama<input class="input" id="name" autocomplete="name" required></label><label>Username<input class="input" id="username" autocomplete="username" required></label></div>':''}<label>Email<input class="input" id="email" type="email" autocomplete="email" required></label><label>Password<input class="input" id="password" type="password" minlength="6" autocomplete="new-password" required></label><div id="err" class="error"></div><button class="goldBtn">${reg?'Buat Akun':'Masuk'}</button></form><div class="switch">${reg?'Sudah punya akun?':'Belum punya akun?'} <button class="link" onclick="${reg?'login()':'register()'}">${reg?'Masuk':'Buat akun'}</button> · <button class="link" onclick="forgot()">Lupa password?</button></div></div></div>`}
async function submitAuth(e,mode){e.preventDefault();const er=document.getElementById('err');if(!state.supabase){er.textContent='Supabase belum terhubung. Periksa Environment Variables Vercel.';return}er.textContent='';
 if(mode==='register'){const {data,error}=await state.supabase.auth.signUp({email:email.value.trim(),password:password.value,data:{name:name.value.trim(),username:username.value.trim(),bio:''}});if(error){er.textContent=error.message;return}if(!data.session){er.textContent='Akun berhasil dibuat. Periksa email untuk konfirmasi, lalu masuk kembali.';return}state.user=data.user;onboarding();}
 else {const {data,error}=await state.supabase.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error){er.textContent=error.message;return}state.user=data.user;renderApp()}}
function forgot(){app.innerHTML=`<div class="authOnly"><div class="authBox authCard"><button class="backBtn" onclick="login()">← Kembali masuk</button><img src="${A}logo.png" class="authLogo small"><p class="eyebrow">PEMULIHAN AKUN</p><h2>Reset password.</h2><p class="sub">Masukkan email dan kami akan mengirimkan instruksi pemulihan.</p><form class="form" onsubmit="submitForgot(event)"><label>Email<input class="input" id="resetEmail" type="email" required></label><div id="err" class="error"></div><button class="goldBtn">Kirim instruksi</button></form></div></div>`}
async function submitForgot(e){e.preventDefault();const er=document.getElementById('err');if(!state.supabase){er.textContent='Supabase belum terhubung.';return}const {error}=await state.supabase.auth.resetPasswordForEmail(resetEmail.value.trim(),{redirectTo:location.origin});er.textContent=error?.message||'Instruksi pemulihan telah dikirim jika email terdaftar.'}

function onboarding(){state.onStep=1;renderOnboarding()}
function renderOnboarding(){const body=state.onStep===1?`<p class="eyebrow">LANGKAH 01</p><h2>Apa yang ingin kamu kembangkan?</h2><p class="sub">Pilih satu atau beberapa ruang yang paling dekat dengan perjalananmu.</p><div class="choices">${['Karya','Bisnis','Karier','Pendidikan','Kehidupan','Kreativitas'].map(x=>`<button class="choice ${state.selected.includes(x)?'selected':''}" onclick="pick('${x}')"><span>${state.selected.includes(x)?'✓':'＋'}</span>${x}</button>`).join('')}</div>`:state.onStep===2?`<p class="eyebrow">LANGKAH 02</p><h2>Ceritakan sedikit tentangmu.</h2><p class="sub">Tidak harus sempurna. Kamu bisa mengubahnya kapan saja.</p><textarea class="input area" id="bio" rows="6" placeholder="Apa yang sedang kamu perjuangkan atau bangun?">${esc(meta().bio||'')}</textarea>`:`<p class="eyebrow">LANGKAH 03</p><h2>Mulai dari satu target.</h2><p class="sub">Target pertama bisa sederhana. Yang penting berarti untukmu.</p><input class="input" id="firstGoal" placeholder="Contoh: menyelesaikan karya pertama saya">`;
 app.innerHTML=`<div class="onboard"><div class="onboardBox"><div class="onboardHead"><img src="${A}logo.png"><div><strong>EA PLAN</strong><span>RUANG PERJALANAN</span></div></div><div class="stepbar">${[1,2,3].map(i=>`<i class="${i<=state.onStep?'active':''}"></i>`).join('')}</div>${body}<div class="actions">${state.onStep>1?'<button class="ghostBtn" onclick="state.onStep--;renderOnboarding()">Kembali</button>':''}<button class="goldBtn" onclick="nextOnboard()">${state.onStep<3?'Lanjut':'Masuk ke EA PLAN'}</button></div></div></div>`}
function pick(x){state.selected=state.selected.includes(x)?state.selected.filter(y=>y!==x):[...state.selected,x];renderOnboarding()}
async function nextOnboard(){if(state.onStep===2&&state.supabase&&state.user)await state.supabase.auth.updateUser({data:{...meta(),bio:document.getElementById('bio').value.trim(),focus:state.selected}});if(state.onStep===3){const g=document.getElementById('firstGoal').value.trim();if(g){const goals=load('goals',[]);goals.unshift({id:uid(),title:g,done:false,created:new Date().toISOString()});save('goals',goals)}renderApp();return}state.onStep++ ;renderOnboarding()}

function renderApp(){state.menu=false;const n=nav.find(x=>x[0]===state.active);const content=pages[state.active]?pages[state.active]():home();app.innerHTML=`<div class="appShell" ${backgroundStyle()}><aside class="side"><div class="sideBrand"><img src="${A}logo.png"><div><b>EA PLAN</b><span>RUANG PERJALANAN</span></div></div><nav class="nav">${nav.map(x=>`<button class="${x[0]===state.active?'active':''}" onclick="go('${x[0]}')"><span class="navIcon">${x[1]}</span><span>${x[2]}</span></button>`).join('')}</nav><div class="sideBottom"><button class="profileNav ${state.active==='profile'?'active':''}" onclick="go('profile')">${avatarMini()}<span>Profil</span></button></div></aside><main class="main"><header class="top"><div><p class="eyebrow">${state.active==='home'?'RUANG PERJALANAN':'EA PLAN'}</p><h2>${n?.[2]||pageTitle()}</h2></div><div class="topActions"><button class="quickBtn" onclick="newItem()">＋ <span>Tambah</span></button><div class="profileWrap"><button class="avatar" onclick="toggleMenu()">${avatarMarkup(true)}</button>${state.menu?profileDropdown():''}</div></div></header>${content}</main><nav class="mobileNav">${[['home','⌂','Beranda'],['planning','☷','Planning'],['goals','◎','Goals'],['journal','✎','Journal'],['profile','◯','Profil']].map(x=>`<button class="${x[0]===state.active?'active':''}" onclick="go('${x[0]}')"><b>${x[1]}</b><span>${x[2]}</span></button>`).join('')}</nav></div>`}
function avatarMarkup(full=false){const u=meta();return u.photo_url?`<img src="${esc(u.photo_url)}" alt="Profil">`:`<span>${initials()}</span>`}
function profileDropdown(){return `<div class="profileMenu"><div class="profileMenuHead">${avatarMini()}<div><b>${esc(meta().name||'Kreator')}</b><span>@${esc(meta().username||'eaplan')}</span></div></div>${profileMenu.map(x=>`<button onclick="go('${x[0]}')">${x[1]}</button>`).join('')}<div class="menuLine"></div><button class="dangerItem" onclick="signOut()">Keluar</button></div>`}
function backgroundStyle(){const bg=meta().background_url;return bg?`style="--user-bg:url('${esc(bg).replace(/'/g,'%27')}');--bg-opacity:.25"`:''}
function pageTitle(){return ({stats:'Statistik',explore:'Jelajahi',collection:'Koleksi',about:'Tentang EA PLAN',guide:'Panduan',profile:'Profil'})[state.active]||'EA PLAN'}
function sectionHead(title,sub=''){return `<div class="sectionHead"><div><p class="eyebrow">EA PLAN</p><h3>${title}</h3>${sub?`<p class="muted">${sub}</p>`:''}</div><button class="linkBtn" onclick="newItem()">＋ Tambah</button></div>`}
function home(){const goals=load('goals',[]),plans=load('plans',[]),projects=load('projects',[]),journals=load('journals',[]),ideas=load('ideas',[]);return `<div class="grid"><article class="card heroCard span8"><div class="heroGlow"></div><div class="eyebrow">SELAMAT DATANG, ${esc((meta().name||'KREATOR').toUpperCase())}</div><h1>Rancang hidupmu.<br><em>Rawat perjalananmu.</em></h1><p>Ruang yang tenang untuk menyusun langkah, menyimpan ide, mengerjakan karya, dan merefleksikan perjalanan.</p><div class="heroActions"><button class="goldBtn" onclick="go('planning')">Lanjutkan perjalanan <span>→</span></button><button class="textBtn" onclick="go('stats')">Lihat statistik</button></div></article><article class="card quoteCard span4"><p class="eyebrow">CATATAN HARI INI</p><blockquote>“Kamu tidak perlu melihat seluruh tangga. Cukup ambil langkah berikutnya.”</blockquote><span>— Ruang refleksi EA PLAN</span></article><article class="card span4"><div class="miniHead"><h3>Target Aktif</h3><button onclick="go('goals')">→</button></div><div class="bigNumber">${goals.filter(g=>!g.done).length}</div><p class="muted">target yang masih berjalan</p><div class="progress"><i style="width:${goals.length?Math.round(goals.filter(g=>g.done).length/goals.length*100):0}%"></i></div></article><article class="card span4"><div class="miniHead"><h3>Projects</h3><button onclick="go('projects')">→</button></div><div class="bigNumber">${projects.length}</div><p class="muted">karya yang sedang kamu bangun</p></article><article class="card span4"><div class="miniHead"><h3>Journal</h3><button onclick="go('journal')">→</button></div><div class="bigNumber">${journals.length}</div><p class="muted">catatan perjalanan tersimpan</p></article><article class="card full"><div class="sectionHead"><div><p class="eyebrow">PILIHAN UNTUKMU</p><h3>Menarik Dilihat</h3></div><button class="linkBtn" onclick="go('explore')">Jelajahi</button></div><div class="workStrip"><div><span class="workTag">KARYA</span><b>Ruang yang sedang tumbuh</b><p>Temukan karya dan cerita dari komunitas EA PLAN.</p></div><div><span class="workTag">IDE</span><b>Catatan kecil, kemungkinan besar</b><p>Ide yang layak disimpan sebelum hilang.</p></div><div><span class="workTag">PERJALANAN</span><b>Langkah yang tidak terlihat</b><p>Refleksi dan proses di balik sebuah karya.</p></div></div></article><article class="card full"><div class="sectionHead"><div><p class="eyebrow">SUARA KOMUNITAS</p><h3>Komentar Mereka</h3></div><button class="linkBtn" onclick="go('explore')">Lihat semua</button></div><div class="comments"><div><span class="commentAvatar">A</span><p><b>Anonim</b> “Ada sesuatu yang jujur dari proses ini.”</p></div><div><span class="commentAvatar">R</span><p><b>Ruang EA</b> “Teruskan. Karya yang baik tumbuh perlahan.”</p></div></div></article></div>`}

const pages={
 planning:()=>module('PLANNING','Susun langkah menjadi sesuatu yang bisa dijalani hari ini.','plans','Rencana baru','Apa langkah berikutnya?','Satu langkah yang jelas lebih berguna daripada daftar yang panjang.'),
 goals:()=>goalsPage(), journal:()=>module('JOURNAL','Tuliskan apa yang terjadi, dirasakan, dan dipelajari.','journals','Catatan baru','Apa yang ingin kamu simpan hari ini?','Tidak perlu sempurna. Tulis apa adanya.'),
 ideas:()=>module('IDEAS','Tangkap ide sebelum ia hilang.','ideas','Ide baru','Apa yang sedang muncul di kepalamu?','Satu kalimat pun cukup untuk memulai.'),
 projects:()=>projectsPage(), journey:()=>journeyPage(), profile:()=>profilePage(), stats:()=>statsPage(), explore:()=>explorePage(), collection:()=>collectionPage(), about:()=>aboutPage(), guide:()=>guidePage()
};
function module(kicker,title,type,button,titlePlaceholder,desc){const items=load(type,[]);return `<div class="pageIntro"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${desc}</p></div><button class="goldBtn" onclick="newItem('${type}')">＋ ${button}</button></div><div class="listGrid">${items.length?items.map((x,i)=>`<article class="listCard"><div class="listMeta"><span>${new Date(x.created).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}</span><button onclick="removeItem('${type}','${x.id}')">×</button></div><h3>${esc(x.title)}</h3>${x.body?`<p>${esc(x.body)}</p>`:''}<div class="listFooter"><span>${i===0?'Terbaru':'Tersimpan'}</span><button onclick="toggleDone('${type}','${x.id}')">${x.done?'✓ Selesai':'Tandai selesai'}</button></div></article>`).join(''):`<div class="emptyState"><span>✦</span><h3>Belum ada ${type==='ideas'?'ide':type==='journals'?'catatan':type==='plans'?'rencana':'item'}.</h3><p>Mulai dari sesuatu yang kecil. Ruang ini akan tumbuh bersamamu.</p><button class="goldBtn" onclick="newItem('${type}')">＋ ${button}</button></div>`}</div>`}
function goalsPage(){const items=load('goals',[]);return `<div class="pageIntro"><div><p class="eyebrow">GOALS</p><h1>Target yang berarti.</h1><p>Ubah niat menjadi target yang bisa kamu lihat, kerjakan, dan rayakan.</p></div><button class="goldBtn" onclick="newItem('goals')">＋ Target baru</button></div><div class="goalList">${items.length?items.map(g=>`<article class="goalCard ${g.done?'done':''}"><button class="check" onclick="toggleDone('goals','${g.id}')">${g.done?'✓':''}</button><div><h3>${esc(g.title)}</h3><span>${g.done?'Selesai':'Sedang berjalan'}</span></div><button class="deleteBtn" onclick="removeItem('goals','${g.id}')">×</button></article>`).join(''):`<div class="emptyState"><span>◎</span><h3>Belum ada target.</h3><p>Mulai dengan satu target yang benar-benar berarti.</p><button class="goldBtn" onclick="newItem('goals')">＋ Buat target</button></div>`}</div>`}
function projectsPage(){const items=load('projects',[]);return `<div class="pageIntro"><div><p class="eyebrow">PROJECTS</p><h1>Bangun karya, tahap demi tahap.</h1><p>Pecah karya besar menjadi ruang kerja yang lebih mudah dijalani.</p></div><button class="goldBtn" onclick="newItem('projects')">＋ Project baru</button></div><div class="projectGrid">${items.length?items.map(p=>`<article class="projectCard"><div class="projectTop"><span>${esc(p.status||'Berjalan')}</span><button onclick="removeItem('projects','${p.id}')">×</button></div><h3>${esc(p.title)}</h3><p>${esc(p.body||'Belum ada deskripsi.')}</p><div class="progress"><i style="width:${p.progress||0}%"></i></div><div class="projectBottom"><span>${p.progress||0}%</span><button onclick="editProgress('${p.id}')">Perbarui progress</button></div></article>`).join(''):`<div class="emptyState"><span>□</span><h3>Belum ada project.</h3><p>Mulai dari karya yang sedang paling ingin kamu selesaikan.</p><button class="goldBtn" onclick="newItem('projects')">＋ Buat project</button></div>`}</div>`}
function journeyPage(){const goals=load('goals',[]),projects=load('projects',[]),journals=load('journals',[]);const total=goals.length+projects.length+journals.length;return `<div class="pageIntro"><div><p class="eyebrow">JOURNEY</p><h1>Perjalananmu, dilihat dari dekat.</h1><p>Bukan hanya hasil akhirnya. Proses, jeda, dan langkah kecil juga bagian dari perjalanan.</p></div></div><div class="timeline"><div class="timelineLine"></div><div class="timelineItem"><span>01</span><div><p class="eyebrow">MULAI</p><h3>Ruangmu telah dibuat.</h3><p>EA PLAN menjadi tempat untuk menyusun perjalananmu.</p></div></div><div class="timelineItem"><span>02</span><div><p class="eyebrow">AKTIVITAS</p><h3>${total} jejak tersimpan.</h3><p>${goals.length} target · ${projects.length} project · ${journals.length} journal.</p></div></div><div class="timelineItem"><span>03</span><div><p class="eyebrow">SELANJUTNYA</p><h3>Satu langkah berikutnya.</h3><p>Pilih satu hal kecil yang bisa kamu kerjakan hari ini.</p></div></div></div>`}
function statsPage(){const goals=load('goals',[]),projects=load('projects',[]),journals=load('journals',[]),ideas=load('ideas',[]);const done=goals.filter(g=>g.done).length, pct=goals.length?Math.round(done/goals.length*100):0;return `<div class="statsHero"><div><p class="eyebrow">STATISTIK</p><h1>Pertumbuhan yang bisa kamu lihat.</h1><p>Gunakan statistik sebagai cermin, bukan tekanan.</p></div><div class="ring" style="--pct:${pct*3.6}deg"><div><b>${pct}%</b><span>Progress</span></div></div></div><div class="statGrid"><article class="statCard"><span>Progress keseluruhan</span><b>${pct}%</b><div class="progress"><i style="width:${pct}%"></i></div></article><article class="statCard"><span>Target Aktif</span><b>${goals.filter(g=>!g.done).length}</b><small>dari ${goals.length} target</small></article><article class="statCard"><span>Projects</span><b>${projects.length}</b><small>karya sedang dibangun</small></article><article class="statCard"><span>Journal</span><b>${journals.length}</b><small>catatan perjalanan</small></article><article class="statCard"><span>Ideas</span><b>${ideas.length}</b><small>kemungkinan tersimpan</small></article><article class="statCard summary"><span>Ringkasan</span><p>${pct>=75?'Perjalananmu sedang bergerak kuat. Pertahankan ritmenya.':pct>=40?'Kamu sudah membangun ritme. Pilih satu langkah berikutnya dan teruskan.':'Setiap langkah kecil tetap berarti. Mulai dari satu hal yang bisa kamu selesaikan hari ini.'}</p></article></div>`}
function profilePage(){const u=meta();return `<div class="profileHero"><div class="profileCover"></div><div class="profileIdentity">${u.photo_url?`<img class="profilePhoto" src="${esc(u.photo_url)}">`:`<div class="profilePhoto placeholder">${initials().slice(0,1)}</div>`}<div><p class="eyebrow">PROFIL KREATOR</p><h1>${esc(u.name||'Kreator')}</h1><p class="handle">@${esc(u.username||'eaplan')}</p><p class="muted">${esc(u.bio||'Belum ada bio. Tambahkan sedikit tentang perjalananmu.')}</p></div><button class="outlineBtn" onclick="editProfile()">Edit profil</button></div></div><div class="profileGrid"><article class="card"><p class="eyebrow">MEDIA PROFIL</p><h3>Foto & background</h3><p class="muted">Gunakan gambar yang membuat ruang ini terasa personal.</p><input class="input" id="profilePhotoInput" type="file" accept="image/*"><input class="input" id="profileBgInput" type="file" accept="image/*"><div id="mediaErr" class="error"></div><button class="goldBtn" onclick="saveMedia()">Simpan media</button></article><article class="card"><p class="eyebrow">KARYA PUBLIK</p><h3>Yang ingin kamu bagikan.</h3><p class="muted">Karya publik akan menjadi jendela perjalananmu untuk komunitas EA PLAN.</p><button class="outlineBtn" onclick="go('explore')">Lihat ruang publik →</button></article><article class="card full"><p class="eyebrow">LAINNYA</p><div class="profileLinks">${[['explore','Karya Publik','Bagikan karya dan temukan karya lain.'],['ideas','Ide & Catatan','Simpan kemungkinan yang sedang tumbuh.'],['projects','Proyek','Kelola karya yang sedang dibangun.'],['journal','Journal','Rawat catatan perjalananmu.'],['journey','Pengalaman','Lihat jejak dan milestone perjalanan.'],['guide','Panduan','Pelajari cara menggunakan EA PLAN.']].map(x=>`<button onclick="go('${x[0]}')"><span><b>${x[1]}</b><small>${x[2]}</small></span><strong>→</strong></button>`).join('')}</div></article></div>`}
function editProfile(){const u=meta();state.modal=`<div class="modal"><div class="modalCard"><button class="modalClose" onclick="closeModal()">×</button><p class="eyebrow">DATA PROFIL</p><h2>Edit profil.</h2><div class="form"><label>Nama<input class="input" id="editName" value="${esc(u.name||'')}"></label><label>Username<input class="input" id="editUsername" value="${esc(u.username||'')}"></label><label>Bio<textarea class="input area" id="editBio">${esc(u.bio||'')}</textarea></label><div id="profileErr" class="error"></div><button class="goldBtn" onclick="saveProfile()">Simpan perubahan</button></div></div></div>`;renderModal()}
function explorePage(){return `<div class="pageIntro"><div><p class="eyebrow">JELAJAHI</p><h1>Karya yang sedang hidup.</h1><p>Ruang publik EA PLAN untuk membaca, menemukan, dan terhubung melalui karya.</p></div></div><div class="exploreGrid"><article class="publicWork featured"><span class="workTag">EDITORIAL</span><h3>Ruang yang belum selesai</h3><p>Tentang keberanian untuk membiarkan sebuah proses tetap menjadi proses.</p><footer>EA PLAN · 6 min read</footer></article><article class="publicWork"><span class="workTag">JOURNAL</span><h3>Hari ketika saya memilih pelan.</h3><p>Catatan tentang ritme, jeda, dan pekerjaan yang tidak terlihat.</p><footer>Anonim · 4 min read</footer></article><article class="publicWork"><span class="workTag">IDE</span><h3>Perpustakaan kecil di kepala.</h3><p>Daftar ide yang mungkin suatu hari menjadi karya.</p><footer>R · 3 min read</footer></article></div>`}
function collectionPage(){return `<div class="pageIntro"><div><p class="eyebrow">KOLEKSI</p><h1>Yang ingin kamu simpan.</h1><p>Tempat untuk mengumpulkan karya, ide, dan referensi yang ingin kembali kamu lihat.</p></div></div><div class="emptyState wideEmpty"><span>♡</span><h3>Koleksimu masih kosong.</h3><p>Saat menemukan sesuatu yang berarti, simpan di sini untuk kembali nanti.</p><button class="goldBtn" onclick="go('explore')">Jelajahi karya</button></div>`}
function aboutPage(){return `<div class="aboutPage"><p class="eyebrow">TENTANG EA PLAN</p><h1>Ruang untuk merancang,<br><em>mencipta, dan bertumbuh.</em></h1><p class="lead">EA PLAN lahir dari gagasan sederhana: hidup yang sedang dibangun layak memiliki ruang yang lebih manusiawi daripada sekadar daftar tugas.</p><div class="aboutColumns"><div><span>01</span><h3>Plan</h3><p>Susun arah dan langkah tanpa kehilangan konteks hidupmu.</p></div><div><span>02</span><h3>Create</h3><p>Ubah ide menjadi karya, project, dan sesuatu yang bisa dibagikan.</p></div><div><span>03</span><h3>Reflect</h3><p>Catat pengalaman agar proses tidak lewat begitu saja.</p></div><div><span>04</span><h3>Grow</h3><p>Lihat pertumbuhan sebagai perjalanan, bukan perlombaan.</p></div></div></div>`}
function guidePage(){return `<div class="guidePage"><p class="eyebrow">PANDUAN</p><h1>Mulai dari yang paling sederhana.</h1><div class="guideList"><article><span>01</span><div><h3>Planning</h3><p>Tambahkan langkah yang ingin kamu jalani. Tidak perlu memuat semuanya sekaligus.</p></div></article><article><span>02</span><div><h3>Goals</h3><p>Simpan target yang berarti dan tandai selesai saat benar-benar tercapai.</p></div></article><article><span>03</span><div><h3>Journal & Ideas</h3><p>Gunakan Journal untuk refleksi dan Ideas untuk menangkap kemungkinan.</p></div></article><article><span>04</span><div><h3>Projects</h3><p>Bangun karya dalam beberapa tahap dan perbarui progress-nya.</p></div></article></div></div>`}

function newItem(type=state.active){const labels={plans:['Rencana baru','Apa langkah yang ingin kamu jalani?'],goals:['Target baru','Apa target yang benar-benar berarti?'],journals:['Journal baru','Apa yang ingin kamu simpan hari ini?'],ideas:['Ide baru','Apa yang sedang muncul di kepalamu?'],projects:['Project baru','Apa karya yang sedang kamu bangun?']};const [title,ph]=labels[type]||labels.plans;state.modal=`<div class="modal"><div class="modalCard"><button class="modalClose" onclick="closeModal()">×</button><p class="eyebrow">${type.toUpperCase()}</p><h2>${title}.</h2><form class="form" onsubmit="createItem(event,'${type}')"><label>Judul<input class="input" id="newTitle" placeholder="${ph}" required></label><label>Catatan / deskripsi<textarea class="input area" id="newBody" placeholder="Tambahkan konteks jika perlu..."></textarea></label>${type==='projects'?'<label>Progress<input class="input" id="newProgress" type="number" min="0" max="100" value="0"></label>':''}<div class="modalActions"><button type="button" class="ghostBtn" onclick="closeModal()">Batal</button><button class="goldBtn">Simpan</button></div></form></div></div>`;renderModal()}
function createItem(e,type){e.preventDefault();const arr=load(type,[]);const item={id:uid(),title:document.getElementById('newTitle').value.trim(),body:document.getElementById('newBody').value.trim(),created:new Date().toISOString(),done:false};if(type==='projects')item.progress=Number(document.getElementById('newProgress').value)||0;arr.unshift(item);save(type,arr);closeModal();renderApp();toast('Tersimpan di ruangmu.')}
function toggleDone(type,id){const arr=load(type,[]);const x=arr.find(a=>a.id===id);if(x)x.done=!x.done;save(type,arr);renderApp()}
function removeItem(type,id){const arr=load(type,[]).filter(x=>x.id!==id);save(type,arr);renderApp();toast('Item dihapus.')}
function editProgress(id){const arr=load('projects',[]),x=arr.find(a=>a.id===id);if(!x)return;const p=prompt('Progress project (0–100)',String(x.progress||0));if(p===null)return;x.progress=Math.max(0,Math.min(100,Number(p)||0));save('projects',arr);renderApp()}
function renderModal(){const old=document.querySelector('.modal');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',state.modal)}
function closeModal(){const m=document.querySelector('.modal');if(m)m.remove();state.modal=null}
async function saveProfile(){const er=document.getElementById('profileErr');if(!state.supabase||!state.user){er.textContent='Sesi Supabase belum tersedia.';return}const payload={...meta(),name:document.getElementById('editName').value.trim()||'Kreator',username:document.getElementById('editUsername').value.trim()||'eaplan',bio:document.getElementById('editBio').value.trim()};const {data,error}=await state.supabase.auth.updateUser({data:payload});if(error){er.textContent=error.message;return}state.user=data.user;closeModal();renderApp();toast('Profil berhasil diperbarui.')}
function fileToPng(file,max=1600){return new Promise((resolve,reject)=>{if(!file)return resolve(null);if(file.size>8*1024*1024)return reject(new Error('Ukuran file maksimal 8 MB.'));const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>b?resolve(b):reject(new Error('Konversi gambar gagal.')),'image/png')};im.onerror=()=>reject(new Error('Gambar tidak valid.'));im.src=r.result};r.onerror=()=>reject(new Error('File tidak dapat dibaca.'));r.readAsDataURL(file)})}
async function saveMedia(){const er=document.getElementById('mediaErr'),p=document.getElementById('profilePhotoInput')?.files[0],b=document.getElementById('profileBgInput')?.files[0];if(!p&&!b){er.textContent='Pilih foto profil atau background terlebih dahulu.';return}if(!state.supabase||!state.user){er.textContent='Sesi Supabase belum tersedia.';return}er.textContent='Mengunggah...';try{const upload=async(file,name,max)=>{if(!file)return null;const blob=await fileToPng(file,max),path=`${state.user.id}/${name}.png`;const {error}=await state.supabase.storage.from('profile-media').upload(path,blob,{contentType:'image/png',upsert:true,cacheControl:'3600'});if(error)throw error;return state.supabase.storage.from('profile-media').getPublicUrl(path).data.publicUrl};const [photo,bg]=await Promise.all([upload(p,'profile',1200),upload(b,'background',2200)]);const {data,error}=await state.supabase.auth.updateUser({data:{...meta(),...(photo?{photo_url:photo}:{}),...(bg?{background_url:bg}:{})}});if(error)throw error;state.user=data.user;renderApp();toast('Media profil berhasil disimpan.')}catch(e){er.textContent=e.message||'Gagal mengunggah media.'}}
function toggleMenu(){state.menu=!state.menu;renderApp()}
function go(id){state.active=id;state.menu=false;renderApp();window.scrollTo({top:0,behavior:'smooth'})}
async function signOut(){if(state.supabase)await state.supabase.auth.signOut();localStorage.removeItem('ea_user');state.user=null;welcome()}
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
boot();
