/* EA PLAN — production Supabase app.js
 * Version: 2026.09.13-auth-production
 * No demo/localStorage authentication.
 */
const A='/public/assets/';
const app=document.getElementById('app');
const nav=[['home','⌂','EA PLAN'],['planning','☷','Planning'],['goals','◎','Goals'],['journal','✎','Journal'],['ideas','✦','Ideas'],['projects','□','Projects'],['journey','↗','Journey'],['stats','◌','Statistik'],['profile','◉','Profil']];
const state={supabase:null,user:null,active:'home',onStep:1,selected:[],bio:'',firstGoal:'',busy:false};
const meta=()=>state.user?.user_metadata||{};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function err(t=''){const e=document.getElementById('err');if(e)e.textContent=t}
function authError(e){const m=String(e?.message||e),x=m.toLowerCase();if(x.includes('user already registered'))return 'Email tersebut sudah terdaftar di EA PLAN.';if(x.includes('invalid login credentials'))return 'Email atau password salah.';if(x.includes('email not confirmed'))return 'Email belum dikonfirmasi. Silakan cek inbox.';if(x.includes('signups not allowed')||x.includes('signup is disabled'))return 'Pendaftaran dinonaktifkan di Supabase. Aktifkan Allow new users to sign up.';if(x.includes('invalid api key'))return 'SUPABASE_ANON_KEY / Publishable Key tidak valid.';if(x.includes('invalid path'))return 'SUPABASE_URL tidak valid. Gunakan https://PROJECT-REF.supabase.co tanpa /rest/v1 atau /auth/v1.';return m}
async function supabaseClient(){
  if(!window.supabase?.createClient)await new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=()=>bad(Error('Supabase JS gagal dimuat.'));document.head.appendChild(s)});
  const r=await fetch('/api/config',{cache:'no-store'});if(!r.ok)throw Error('Config API gagal ('+r.status+').');
  const c=await r.json(),url=String(c.url||'').trim(),key=String(c.anonKey||'').trim();
  if(!url||!key)throw Error('SUPABASE_URL atau SUPABASE_ANON_KEY belum tersedia di Vercel.');
  if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(url))throw Error('SUPABASE_URL tidak valid: '+url);
  return window.supabase.createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
}
function splash(){app.innerHTML=`<div class="splash"><img class="bg" src="${A}splash.jpg"><div class="content"><img class="logo" src="${A}logo.png"><div class="word">EA PLAN</div><div class="tag">YOUR PERSONALIZED PLANNING JOURNEY</div></div></div>`}
function welcome(){app.innerHTML=`<div class="authShell"><div class="authVisual"><img src="${A}splash.jpg"><div class="visualText"><div class="ey">PLAN · CREATE · REFLECT · GROW</div><h1>Rancang hidupmu.<br>Rawat perjalananmu.</h1><p>Ruang untuk merencanakan langkah, menyimpan ide, menulis cerita, mengelola proyek, dan melihat pertumbuhan.</p></div></div><div class="authPanel"><div class="authBox"><img class="miniLogo" src="${A}logo.png"><div class="brandText">EA PLAN</div><h2>Mulai perjalananmu.</h2><p class="sub">Satu langkah kecil hari ini dapat menjadi bagian dari karya besar esok hari.</p><div class="form"><button class="goldBtn" onclick="window.register()">Buat Akun</button><button class="ghostBtn" onclick="window.login()">Sudah punya akun? Masuk</button></div><p class="switch">Akun dikelola oleh Supabase Auth.</p></div></div></div>`}
function auth(mode){const reg=mode==='register';app.innerHTML=`<div class="authPanel ea-bg-page" style="min-height:100vh;color:white"><div class="authBox"><button class="link" onclick="window.welcome()">← Kembali</button><div style="text-align:center"><img class="miniLogo" src="${A}logo.png"></div><div class="brandText">EA PLAN</div><div class="kicker" style="margin-top:28px">MEMULAI RUANGMU</div><h2>${reg?'Buat akun.':'Selamat datang kembali.'}</h2><p class="sub">${reg?'Bangun ruang perjalanan yang terasa milikmu.':'Masuk untuk melanjutkan perjalananmu.'}</p><form class="form" id="authForm">${reg?'<label class="label">Nama<input class="input" id="name" autocomplete="name" required></label><label class="label">Username<input class="input" id="username" autocomplete="username" required></label>':''}<label class="label">Email<input class="input" id="email" type="email" autocomplete="email" required></label><label class="label">Password<input class="input" id="password" type="password" minlength="6" autocomplete="${reg?'new-password':'current-password'}" required></label><div id="err" class="error"></div><button class="goldBtn" type="submit" data-auth-submit>${reg?'Buat Akun':'Masuk'}</button></form><div class="switch">${reg?'Sudah punya akun? <button class="link" onclick="window.login()">Masuk</button>':'Belum punya akun? <button class="link" onclick="window.register()">Buat akun</button> · <button class="link" onclick="window.forgot()">Lupa password?</button>'}</div></div></div>`;document.getElementById('authForm').addEventListener('submit',e=>submitAuth(e,mode))}
async function submitAuth(e,mode){e.preventDefault();if(state.busy)return;const email=(document.getElementById('email')?.value||'').trim().toLowerCase(),password=document.getElementById('password')?.value||'';if(!email||!password)return err('Email dan password wajib diisi.');if(!state.supabase)return err('Supabase belum terhubung. Periksa Environment Variables Vercel.');state.busy=true;const b=document.querySelector('[data-auth-submit]');if(b){b.disabled=true;b.textContent='Memproses...'};try{if(mode==='register'){const name=document.getElementById('name').value.trim(),username=document.getElementById('username').value.trim();if(!name||!username)throw Error('Nama dan username wajib diisi.');const {data,error}=await state.supabase.auth.signUp({email,password,options:{data:{name,username,onboarding_complete:false,focus:[],bio:'',first_goal:''}}});if(error)throw error;if(!data.user)throw Error('Supabase tidak mengembalikan user.');state.user=data.user;state.selected=[];state.onStep=1;if(data.session)onboarding();else{app.innerHTML=`<div class="authPanel ea-bg-page" style="min-height:100vh;color:white"><div class="authBox"><div class="kicker">AKUN DIBUAT</div><h2>Cek email kamu.</h2><p class="sub">Konfirmasi email terlebih dahulu, lalu masuk kembali ke EA PLAN.</p><button class="goldBtn" onclick="window.login()">Masuk</button></div></div>`}return}const {data,error}=await state.supabase.auth.signInWithPassword({email,password});if(error)throw error;if(!data.session)throw Error('Login berhasil tetapi sesi tidak tersedia.');state.user=data.user;meta().onboarding_complete===true?dashboard():onboarding()}catch(x){console.error('[EA PLAN AUTH]',x);err(authError(x))}finally{state.busy=false;if(b){b.disabled=false;b.textContent=mode==='register'?'Buat Akun':'Masuk'}}}
function forgot(){app.innerHTML=`<div class="authPanel ea-bg-page" style="min-height:100vh;color:white"><div class="authBox"><button class="link" onclick="window.login()">← Kembali</button><div class="brandText">EA PLAN</div><h2>Reset password.</h2><p class="sub">Masukkan email akun EA PLAN.</p><form class="form" id="forgotForm"><input class="input" id="resetEmail" type="email" required placeholder="Email"><div id="err" class="error"></div><button class="goldBtn">Kirim instruksi</button></form></div></div>`;document.getElementById('forgotForm').addEventListener('submit',async e=>{e.preventDefault();try{const {error}=await state.supabase.auth.resetPasswordForEmail(document.getElementById('resetEmail').value.trim().toLowerCase(),{redirectTo:location.origin+'/'});if(error)throw error;e.target.innerHTML='<div class="sub">Instruksi reset password telah diminta. Cek inbox email Anda.</div>'}catch(x){err(authError(x))}})}
function onboarding(){state.onStep=1;state.selected=Array.isArray(meta().focus)?meta().focus:[];state.bio=meta().bio||'';state.firstGoal=meta().first_goal||'';renderOnboarding()}
function renderOnboarding(){let body;if(state.onStep===1){const c=['Karya','Bisnis','Karier','Pendidikan','Kehidupan','Kreativitas'];body=`<div class="kicker">LANGKAH 1</div><h2>Apa yang ingin kamu kembangkan?</h2><p class="sub">Pilih yang paling dekat dengan perjalananmu.</p><div class="choices">${c.map(x=>`<button class="choice ${state.selected.includes(x)?'selected':''}" onclick="window.pickFocus('${x}')">${state.selected.includes(x)?'✓':'○'} ${x}</button>`).join('')}</div>`}else if(state.onStep===2)body=`<div class="kicker">LANGKAH 2</div><h2>Ceritakan sedikit tentangmu.</h2><p class="sub">Bagian ini opsional.</p><textarea class="input" id="bio" rows="6">${esc(state.bio)}</textarea>`;else body=`<div class="kicker">LANGKAH 3</div><h2>Apa target utamamu?</h2><p class="sub">Mulai dari satu target yang berarti.</p><input class="input" id="firstGoal" value="${esc(state.firstGoal)}" placeholder="Contoh: menyelesaikan karya pertama saya">`;app.innerHTML=`<div class="onboard ea-bg-page"><div class="onboardBox"><div class="brandText">EA PLAN</div><div class="steps"><i class="${state.onStep>=1?'active':''}"></i><i class="${state.onStep>=2?'active':''}"></i><i class="${state.onStep>=3?'active':''}"></i></div>${body}<div class="actions">${state.onStep>1?'<button class="ghostBtn" onclick="window.prevOnboard()">Kembali</button>':''}<button class="goldBtn" onclick="window.nextOnboard()">${state.onStep<3?'Lanjut':'Masuk ke EA PLAN'}</button></div></div></div>`}
function pickFocus(x){state.selected=state.selected.includes(x)?state.selected.filter(v=>v!==x):[...state.selected,x];renderOnboarding()}
function prevOnboard(){if(state.onStep===3)state.firstGoal=document.getElementById('firstGoal')?.value.trim()||state.firstGoal;if(state.onStep>1){state.onStep--;renderOnboarding()}}
async function nextOnboard(){if(state.onStep===1){state.onStep=2;renderOnboarding();return}if(state.onStep===2){state.bio=document.getElementById('bio')?.value.trim()||'';state.onStep=3;renderOnboarding();return}state.firstGoal=document.getElementById('firstGoal')?.value.trim()||'';try{const {data,error}=await state.supabase.auth.updateUser({data:{...meta(),focus:state.selected,bio:state.bio,first_goal:state.firstGoal,onboarding_complete:true}});if(error)throw error;state.user=data.user;dashboard()}catch(x){alert(authError(x))}}
function dashboard(){state.active='home';renderApp()}
function renderApp(){const n=nav.find(x=>x[0]===state.active)||nav[0],content=page(n[0],n[2]);app.innerHTML=`<div class="ea-bg-page"><div class="appShell"><aside class="side"><div class="sideBrand"><img src="${A}logo.png"><span>EA PLAN</span></div><nav class="nav">${nav.map(x=>`<button class="${x[0]===state.active?'active':''}" onclick="window.go('${x[0]}')">${x[1]}&nbsp;&nbsp;${x[2]}</button>`).join('')}<button onclick="window.signOut()">↪&nbsp;&nbsp;Keluar</button></nav></aside><main class="main"><header class="top"><div><div class="kicker">RUANG PERJALANAN</div><h2>${esc(n[2])}</h2></div><button class="avatar" onclick="window.go('profile')">${esc((meta().name||'EA').slice(0,2).toUpperCase())}</button></header>${content}</main><nav class="mobileNav">${nav.slice(0,5).map(x=>`<button class="${x[0]===state.active?'active':''}" onclick="window.go('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav></div></div>`}
function page(id,title){if(id==='home')return `<div class="grid"><article class="card full"><div class="kicker">SELAMAT DATANG, ${esc((meta().name||'KREATOR').toUpperCase())}</div><h1 style="font:500 42px Georgia,serif;margin:12px 0">Rancang hidupmu.<br>Rawat perjalananmu.</h1><p class="muted">“Setiap karya besar berawal dari satu langkah kecil yang terencana.”</p></article><article class="card"><div class="kicker">TARGET</div><h3>${esc(meta().first_goal||'Belum ada target utama')}</h3></article><article class="card"><div class="kicker">FOKUS</div><h3>${esc((meta().focus||[]).join(' · ')||'Belum dipilih')}</h3></article><article class="card"><div class="kicker">AKUN</div><h3>Supabase Auth</h3><p class="muted">Sesi akun aktif.</p></article></div>`;if(id==='stats')return `<div class="grid"><article class="card"><div class="kicker">PROGRESS KESELURUHAN</div><div class="metric">0%</div><div class="progress"><i style="width:0"></i></div></article><article class="card"><div class="kicker">TARGET AKTIF</div><div class="metric">0</div></article><article class="card"><div class="kicker">PROJECTS</div><div class="metric">0</div></article><article class="card"><div class="kicker">JOURNAL</div><div class="metric">0</div></article><article class="card"><div class="kicker">IDEAS</div><div class="metric">0</div></article><article class="card full"><h3>Ringkasan</h3><p class="muted">Statistik akan terisi ketika data modul CRUD diaktifkan.</p></article></div>`;if(id==='profile')return `<div class="grid"><article class="card wide"><div class="kicker">MEDIA PROFIL</div><h2 style="font-family:Georgia,serif">${esc(meta().name||'Nama pengguna')}</h2><p class="muted">@${esc(meta().username||'username')}</p></article><article class="card"><div class="kicker">EMAIL</div><p>${esc(state.user?.email||'')}</p></article><article class="card full"><div class="kicker">TENTANGMU</div><p class="muted">${esc(meta().bio||'Belum ada bio.')}</p></article></div>`;return `<div class="grid"><article class="card full"><div class="kicker">EA PLAN</div><h1 style="font:500 40px Georgia,serif">${esc(title)}</h1><p class="muted">Modul ${esc(title)} sudah terhubung ke akun Supabase. CRUD cloud dapat dikembangkan di tahap berikutnya.</p></article></div>`}
function go(id){state.active=id;renderApp()}
async function signOut(){try{await state.supabase.auth.signOut()}finally{state.user=null;welcome()}}
Object.assign(window,{register:()=>auth('register'),login:()=>auth('login'),welcome,forgot,pickFocus,prevOnboard,nextOnboard,go,signOut});
(async function boot(){splash();try{state.supabase=await supabaseClient();const {data:{session}}=await state.supabase.auth.getSession();state.user=session?.user||null;state.supabase.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null});setTimeout(()=>state.user?(meta().onboarding_complete===true?dashboard():onboarding()):welcome(),1400)}catch(x){console.error('[EA PLAN BOOT]',x);setTimeout(()=>{app.innerHTML=`<div class="authPanel ea-bg-page" style="min-height:100vh;color:white"><div class="authBox"><div class="brandText">EA PLAN</div><h2>Supabase belum terhubung.</h2><p class="sub">${esc(authError(x))}</p><button class="goldBtn" onclick="location.reload()">Coba lagi</button></div></div>`},1400)}})();
