const A='/assets/';
const app=document.querySelector('#app');
const nav=[['home','⌂','Beranda'],['planning','☷','Planning'],['goals','◎','Goals'],['journal','✎','Journal'],['ideas','✦','Ideas'],['projects','□','Projects'],['journey','↗','Journey'],['profile','◯','Profil']];
let state={user:null,selected:[],onStep:1,active:'home',supabase:null};

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const userMeta=()=>state.user?.user_metadata||{};

async function boot(){
  splash();
  state.supabase=await window.EA_SUPABASE_READY;
  if(!state.supabase){
    setTimeout(()=>{state.user=JSON.parse(localStorage.getItem('ea_user')||'null');state.user?dashboard():welcome()},3000);
    return;
  }
  const {data:{session}}=await state.supabase.auth.getSession();
  state.user=session?.user||null;
  state.supabase.auth.onAuthStateChange((_event,session)=>{state.user=session?.user||null;if(session) renderApp();});
  setTimeout(()=>{if(state.user)dashboard();else welcome()},3000);
}

function splash(){app.innerHTML=`<div class="splash"><img class="bg" src="${A}splash.jpg"><div class="content"><img class="logo" src="${A}logo.png"><div class="tag">YOUR PERSONALIZED PLANNING JOURNEY</div></div></div>`}
function welcome(){app.innerHTML=`<div class="authShell"><div class="authVisual"><img src="${A}splash.jpg"><div class="visualText"><div class="ey">PLAN · CREATE · REFLECT · GROW</div><h1>Rancang hidupmu.<br>Rawat perjalananmu.</h1><p>Ruang untuk merencanakan langkah, menyimpan ide, menulis cerita, mengelola proyek, dan melihat pertumbuhan dari waktu ke waktu.</p></div></div><div class="authPanel"><div class="authBox"><img class="miniLogo" src="${A}logo.png"><h2>Mulai perjalananmu.</h2><p class="sub">Satu langkah kecil hari ini dapat menjadi bagian dari karya besar esok hari.</p><div class="form"><button class="goldBtn" onclick="register()">Buat Akun</button><button class="ghostBtn" onclick="login()">Sudah punya akun? Masuk</button></div><p class="switch">Dengan melanjutkan, kamu menyetujui ruang privat dan publik EA PLAN yang akan dijelaskan saat akun dibuat.</p></div></div></div>`}
function register(){auth('register')}function login(){auth('login')}
function auth(mode){let reg=mode==='register';app.innerHTML=`<div class="authPanel" style="min-height:100vh;background:radial-gradient(circle at top,#3a2a1c,#17130f 50%);color:white"><div class="authBox"><img class="miniLogo" src="${A}logo.png"><h2>${reg?'Buat akun.':'Selamat datang kembali.'}</h2><p class="sub">${reg?'Buat ruang perjalanan pribadimu.':'Masuk untuk melanjutkan perjalananmu.'}</p><form class="form" onsubmit="submitAuth(event,'${mode}')">${reg?'<input class="input" id="name" placeholder="Nama" required><input class="input" id="username" placeholder="Username" required>':''}<input class="input" id="email" type="email" placeholder="Email" required><input class="input" id="password" type="password" placeholder="Password" minlength="6" required><div id="err" class="error"></div><button class="goldBtn">${reg?'Buat Akun':'Masuk'}</button></form><div class="switch"><button class="link" onclick="welcome()">← Kembali</button> · <button class="link" onclick="forgot()">Lupa password?</button></div></div></div>`}
async function submitAuth(e,mode){e.preventDefault();
  if(!state.supabase){err.textContent='Supabase belum terhubung. Isi Environment Variables di Vercel terlebih dahulu.';return}
  err.textContent='';
  if(mode==='register'){
    const {data,error}=await state.supabase.auth.signUp({email:email.value.trim(),password:password.value,data:{name:name.value.trim(),username:username.value.trim(),bio:''}});
    if(error){err.textContent=error.message;return}
    if(!data.session){err.textContent='Akun dibuat. Jika konfirmasi email aktif, cek email lalu masuk kembali.';return}
    state.user=data.user;onboarding();
  }else{
    const {data,error}=await state.supabase.auth.signInWithPassword({email:email.value.trim(),password:password.value});
    if(error){err.textContent=error.message;return}
    state.user=data.user;dashboard();
  }
}
async function forgot(){app.innerHTML=`<div class="authPanel" style="min-height:100vh;background:var(--black);color:white"><div class="authBox"><img class="miniLogo" src="${A}logo.png"><h2>Reset password.</h2><p class="sub">Masukkan email untuk menerima instruksi pemulihan akun.</p><form class="form" onsubmit="submitForgot(event)"><input class="input" id="resetEmail" type="email" placeholder="Email" required><div id="err" class="error"></div><button class="goldBtn">Kirim instruksi</button></form><div class="switch"><button class="link" onclick="login()">← Kembali masuk</button></div></div></div>`}
async function submitForgot(e){e.preventDefault();if(!state.supabase){err.textContent='Supabase belum terhubung.';return}const {error}=await state.supabase.auth.resetPasswordForEmail(resetEmail.value.trim(),{redirectTo:location.origin});if(error)err.textContent=error.message;else alert('Instruksi reset password telah dikirim jika email terdaftar.');}

function onboarding(){state.onStep=1;renderOnboarding()}
function renderOnboarding(){let steps=['Fokus','Tentangmu','Target'];let body=state.onStep===1?`<div class="kicker">LANGKAH 1</div><h2>Apa yang ingin kamu kembangkan?</h2><p class="sub">Pilih yang paling dekat dengan perjalananmu. Kamu bisa memilih lebih dari satu.</p><div class="choices">${['Karya','Bisnis','Karier','Pendidikan','Kehidupan','Kreativitas'].map(x=>`<button class="choice ${state.selected.includes(x)?'selected':''}" onclick="pick('${x}')">${state.selected.includes(x)?'✓ ':'○ '}${x}</button>`).join('')}</div>`:state.onStep===2?`<div class="kicker">LANGKAH 2</div><h2>Ceritakan sedikit tentangmu.</h2><p class="sub">Bagian ini opsional. Profil dapat kamu ubah nanti.</p><textarea class="input" id="bio" rows="6" placeholder="Apa yang sedang kamu perjuangkan atau bangun?"></textarea>`:`<div class="kicker">LANGKAH 3</div><h2>Apa target utamamu?</h2><p class="sub">Kita mulai dari satu target yang benar-benar berarti.</p><input class="input" id="firstGoal" placeholder="Contoh: menyelesaikan karya pertama saya">`;app.innerHTML=`<div class="onboard"><div class="onboardBox"><div class="steps">${steps.map((_,i)=>`<i class="${i+1<=state.onStep?'active':''}"></i>`).join('')}</div>${body}<div class="actions">${state.onStep>1?'<button class="ghostBtn" onclick="state.onStep--;renderOnboarding()">Kembali</button>':''}<button class="goldBtn" onclick="nextOnboard()">${state.onStep<3?'Lanjut':'Masuk ke EA PLAN'}</button></div></div></div>`}
function pick(x){state.selected=state.selected.includes(x)?state.selected.filter(y=>y!==x):[...state.selected,x];renderOnboarding()}
async function nextOnboard(){if(state.onStep<3){if(state.onStep===2&&state.supabase&&state.user){await state.supabase.auth.updateUser({data:{bio:bio.value.trim()}})}state.onStep++;renderOnboarding()}else dashboard()}
function dashboard(){state.active='home';renderApp()}
function backgroundStyle(){const bg=userMeta().background_url;return bg?`style="--user-bg:url('${esc(bg).replace(/'/g,"%27")}')"`:''}
function renderApp(){let n=nav.find(x=>x[0]===state.active)||nav[0];let content=state.active==='home'?home():state.active==='profile'?profile():modulePage(n[1],n[2]);app.innerHTML=`<div class="appShell" ${backgroundStyle()}><aside class="side"><div class="sideBrand"><img src="${A}logo.png"><span>EA PLAN</span></div><nav class="nav">${nav.map(x=>`<button class="${x[0]===state.active?'active':''}" onclick="go('${x[0]}')">${x[1]}&nbsp;&nbsp;${x[2]}</button>`).join('')}</nav></aside><main class="main"><header class="top"><div><div class="kicker">RUANG PERJALANAN</div><h2>${n[2]}</h2></div><button class="avatar" onclick="go('profile')" aria-label="Profil">${userMeta().photo_url?`<img src="${esc(userMeta().photo_url)}" alt="Profil">`:(userMeta().name||state.user?.email||'EA').slice(0,2).toUpperCase()}</button></header>${content}</main><nav class="mobileNav">${nav.slice(0,5).map(x=>`<button class="${x[0]===state.active?'active':''}" onclick="go('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav></div>`}
function home(){return `<div class="grid"><article class="card wide heroHome"><div class="kicker">SELAMAT DATANG, ${esc((userMeta().name||'KREATOR').toUpperCase())}</div><h1>Rancang hidupmu.<br>Rawat perjalananmu.</h1><p class="muted">“Setiap karya besar berawal dari satu langkah kecil yang terencana.”</p></article><article class="card full"><div class="sectionHead"><h3>Terbaru</h3><button class="linkBtn">Lihat semua</button></div><p class="muted">Belum ada karya publik. Jadilah kreator pertama.</p></article><article class="card full"><div class="sectionHead"><h3>Terpopuler</h3><button class="linkBtn">Lihat semua</button></div><p class="muted">Karya populer akan tampil di sini setelah tersedia.</p></article><article class="card full"><div class="sectionHead"><h3>Menarik Dilihat</h3><button class="linkBtn">Lihat semua</button></div><p class="muted">Temukan karya yang menarik dari komunitas EA PLAN.</p></article><article class="card full"><div class="sectionHead"><h3>Komentar Mereka</h3><button class="linkBtn">Lihat semua</button></div><p class="muted">Komentar pada karya publik akan muncul di sini.</p></article></div>`}
function profile(){let u=userMeta();return `<div class="grid"><article class="card full profileCard"><div class="profileTop">${u.photo_url?`<img class="profilePhoto" src="${esc(u.photo_url)}" alt="Foto profil">`:`<div class="profilePhoto placeholder">${esc((u.name||'A').slice(0,1).toUpperCase())}</div>`}<div><div class="kicker">PROFIL KREATOR</div><h1>${esc(u.name||'Ari')}</h1><p class="muted">@${esc(u.username||'ari')}</p><p class="muted">${esc(u.bio||'Belum ada bio.')}</p></div></div><div class="statsMini"><span><b>0</b>Karya</span><span><b>0</b>Projects</span><span><b>0</b>Journal</span><span><b>0%</b>Progress</span></div></article><article class="card full"><div class="kicker">MEDIA PROFIL</div><p class="muted">Foto profil disimpan ke Supabase Storage. File foto akan dikonversi ke PNG sebelum diunggah.</p><label class="label">Foto profil</label><input class="input" id="profilePhotoInput" type="file" accept="image/*"><label class="label">Background</label><input class="input" id="profileBgInput" type="file" accept="image/*"><div id="mediaErr" class="error"></div><button class="goldBtn" onclick="saveMedia()">Simpan foto & background</button></article><article class="card full"><div class="kicker">DATA PROFIL</div><div class="form"><input class="input" id="profileName" value="${esc(u.name||'')}" placeholder="Nama"><input class="input" id="profileUsername" value="${esc(u.username||'')}" placeholder="Username"><textarea class="input" id="profileBio" rows="5" placeholder="Bio">${esc(u.bio||'')}</textarea><div id="profileErr" class="error"></div><button class="goldBtn" onclick="saveProfile()">Simpan profil</button></div></article></div>`}
async function saveProfile(){if(!state.supabase||!state.user){profileErr.textContent='Sesi Supabase belum tersedia.';return}profileErr.textContent='Menyimpan...';const {data,error}=await state.supabase.auth.updateUser({data:{...userMeta(),name:profileName.value.trim()||'Ari',username:profileUsername.value.trim()||'ari',bio:profileBio.value.trim()}});if(error){profileErr.textContent=error.message;return}state.user=data.user;renderApp();alert('Profil berhasil disimpan.')}
function fileToPng(file,max=1600){return new Promise((resolve,reject)=>{if(!file){resolve(null);return}if(file.size>8*1024*1024){reject(new Error('Ukuran file maksimal 8 MB.'));return}const r=new FileReader();r.onerror=()=>reject(new Error('File tidak dapat dibaca.'));r.onload=()=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(blob=>blob?resolve(blob):reject(new Error('Konversi PNG gagal.')),'image/png');};img.onerror=()=>reject(new Error('Gambar tidak valid.'));img.src=r.result};r.readAsDataURL(file)})}
async function uploadMedia(file,kind){if(!file)return null;const blob=await fileToPng(file,kind==='avatar'?1200:2000);const path=`${state.user.id}/${kind}.png`;const {error}=await state.supabase.storage.from('profile-media').upload(path,blob,{contentType:'image/png',upsert:true,cacheControl:'3600'});if(error)throw error;const {data}=state.supabase.storage.from('profile-media').getPublicUrl(path);return data.publicUrl}
async function saveMedia(){const mediaErr=document.getElementById('mediaErr');if(!state.supabase||!state.user){mediaErr.textContent='Sesi Supabase belum tersedia. Silakan masuk kembali.';return}const p=profilePhotoInput.files[0],b=profileBgInput.files[0];if(!p&&!b){mediaErr.textContent='Pilih foto profil atau background terlebih dahulu.';return}mediaErr.textContent='Mengunggah ke Supabase Storage...';try{const [photoUrl,bgUrl]=await Promise.all([uploadMedia(p,'profile'),uploadMedia(b,'background')]);const meta={...userMeta(),...(photoUrl?{photo_url:photoUrl}:{}),...(bgUrl?{background_url:bgUrl}:{})};const {data,error}=await state.supabase.auth.updateUser({data:meta});if(error)throw error;state.user=data.user;renderApp();alert('Media profil berhasil disimpan di Supabase Storage.')}catch(e){mediaErr.textContent=e.message||'Gagal mengunggah media.'}}
function modulePage(a,b){return `<div class="grid"><article class="card full"><div class="kicker">EA PLAN</div><h1 style="font:500 40px Georgia,serif">${b}</h1><p class="muted">${a==='Planning'?'Susun langkah dengan sederhana.':a==='Goals'?'Ubah mimpi menjadi target yang terukur.':a==='Journal'?'Tulis apa yang terjadi, dirasakan, dan dipelajari.':a==='Ideas'?'Tangkap ide sebelum hilang.':a==='Projects'?'Pecah karya besar menjadi tahapan kecil.':'Lihat milestone dan pertumbuhanmu dari waktu ke waktu.'}</p><div class="item">Modul ini sudah memiliki tempat di arsitektur production EA PLAN. CRUD + cloud database akan diaktifkan pada fase berikutnya.</div></article></div>`}
async function signOut(){if(state.supabase)await state.supabase.auth.signOut();state.user=null;welcome()}
function go(id){state.active=id;renderApp()}
boot();
